import { config as loadEnv } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
loadEnv({ path: resolve(dirname(fileURLToPath(import.meta.url)), '../.env') });

const BASE = 'http://localhost:3000';
const SECRET = process.env.ADMIN_SECRET!;
const headers = { 'Content-Type': 'application/json', 'X-Admin-Secret': SECRET };

type PT = 'privacy_policy' | 'terms_of_service' | 'data_processing_agreement' | 'acceptable_use_policy';
interface C { domain: string; name: string; product?: string; policyType: PT; priority: number; notes?: string; }

const CANDIDATES: C[] = [
  // ── SaaS / B2B ────────────────────────────────────────────────────────────
  { domain: 'salesforce.com',      name: 'Salesforce',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'salesforce.com',      name: 'Salesforce',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'salesforce.com',      name: 'Salesforce',     policyType: 'data_processing_agreement', priority: 2, notes: 'CRM — holds customer contact and sales data for businesses' },
  { domain: 'hubspot.com',         name: 'HubSpot',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'hubspot.com',         name: 'HubSpot',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'hubspot.com',         name: 'HubSpot',        policyType: 'data_processing_agreement', priority: 2 },
  { domain: 'slack.com',           name: 'Slack',          policyType: 'privacy_policy',   priority: 1, notes: 'Work communications — messages, files, DMs' },
  { domain: 'slack.com',           name: 'Slack',          policyType: 'terms_of_service', priority: 1 },
  { domain: 'slack.com',           name: 'Slack',          policyType: 'data_processing_agreement', priority: 2 },
  { domain: 'notion.so',           name: 'Notion',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'notion.so',           name: 'Notion',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'airtable.com',        name: 'Airtable',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'airtable.com',        name: 'Airtable',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'figma.com',           name: 'Figma',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'figma.com',           name: 'Figma',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'atlassian.com',       name: 'Atlassian',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'atlassian.com',       name: 'Atlassian',      policyType: 'terms_of_service', priority: 2 },
  { domain: 'atlassian.com',       name: 'Atlassian',      product: 'Jira',                policyType: 'terms_of_service', priority: 2 },
  { domain: 'atlassian.com',       name: 'Atlassian',      product: 'Confluence',          policyType: 'terms_of_service', priority: 3 },
  { domain: 'zendesk.com',         name: 'Zendesk',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'zendesk.com',         name: 'Zendesk',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'intercom.com',        name: 'Intercom',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'mailchimp.com',       name: 'Mailchimp',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'mailchimp.com',       name: 'Mailchimp',      policyType: 'terms_of_service', priority: 2 },
  { domain: 'constantcontact.com', name: 'Constant Contact', policyType: 'privacy_policy', priority: 3 },
  { domain: 'sendgrid.com',        name: 'SendGrid / Twilio', policyType: 'privacy_policy', priority: 2 },
  { domain: 'twilio.com',          name: 'Twilio',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'twilio.com',          name: 'Twilio',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'segment.com',         name: 'Segment',        policyType: 'privacy_policy',   priority: 1, notes: 'Customer data platform — aggregates user events across products' },
  { domain: 'segment.com',         name: 'Segment',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'mixpanel.com',        name: 'Mixpanel',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'amplitude.com',       name: 'Amplitude',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'datadog.com',         name: 'Datadog',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'datadog.com',         name: 'Datadog',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'newrelic.com',        name: 'New Relic',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'sentry.io',           name: 'Sentry',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'pagerduty.com',       name: 'PagerDuty',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'cloudflare.com',      name: 'Cloudflare',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'cloudflare.com',      name: 'Cloudflare',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'vercel.com',          name: 'Vercel',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'vercel.com',          name: 'Vercel',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'netlify.com',         name: 'Netlify',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'netlify.com',         name: 'Netlify',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'heroku.com',          name: 'Heroku',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'digitalocean.com',    name: 'DigitalOcean',   policyType: 'privacy_policy',   priority: 2 },
  { domain: 'digitalocean.com',    name: 'DigitalOcean',   policyType: 'terms_of_service', priority: 3 },
  { domain: 'linode.com',          name: 'Linode / Akamai', policyType: 'privacy_policy',  priority: 3 },
  { domain: 'asana.com',           name: 'Asana',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'asana.com',           name: 'Asana',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'monday.com',          name: 'Monday.com',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'monday.com',          name: 'Monday.com',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'trello.com',          name: 'Trello',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'basecamp.com',        name: 'Basecamp',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'dropbox.com',         name: 'Dropbox',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'dropbox.com',         name: 'Dropbox',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'box.com',             name: 'Box',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'box.com',             name: 'Box',            policyType: 'terms_of_service', priority: 2 },
  { domain: 'docusign.com',        name: 'DocuSign',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'docusign.com',        name: 'DocuSign',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'calendly.com',        name: 'Calendly',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'loom.com',            name: 'Loom',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'miro.com',            name: 'Miro',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'typeform.com',        name: 'Typeform',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'surveymonkey.com',    name: 'SurveyMonkey',   policyType: 'privacy_policy',   priority: 3 },
  { domain: 'clickup.com',         name: 'ClickUp',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'smartsheet.com',      name: 'Smartsheet',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hotjar.com',          name: 'Hotjar',         policyType: 'privacy_policy',   priority: 2, notes: 'Session recording, heatmaps — captures user behavior on client sites' },
  { domain: 'fullstory.com',       name: 'FullStory',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'klaviyo.com',         name: 'Klaviyo',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'klaviyo.com',         name: 'Klaviyo',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'braze.com',           name: 'Braze',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'wordpress.com',       name: 'WordPress.com',  policyType: 'privacy_policy',   priority: 2 },
  { domain: 'wordpress.com',       name: 'WordPress.com',  policyType: 'terms_of_service', priority: 2 },
  { domain: 'wix.com',             name: 'Wix',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'wix.com',             name: 'Wix',            policyType: 'terms_of_service', priority: 2 },
  { domain: 'squarespace.com',     name: 'Squarespace',    policyType: 'privacy_policy',   priority: 2 },
  { domain: 'squarespace.com',     name: 'Squarespace',    policyType: 'terms_of_service', priority: 2 },
  { domain: 'webflow.com',         name: 'Webflow',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'webflow.com',         name: 'Webflow',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'framer.com',          name: 'Framer',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'godaddy.com',         name: 'GoDaddy',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'godaddy.com',         name: 'GoDaddy',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'namecheap.com',       name: 'Namecheap',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'postman.com',         name: 'Postman',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'postman.com',         name: 'Postman',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'docker.com',          name: 'Docker',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'docker.com',          name: 'Docker',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'jetbrains.com',       name: 'JetBrains',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'jetbrains.com',       name: 'JetBrains',      policyType: 'terms_of_service', priority: 3 },
  { domain: 'npmjs.com',           name: 'npm',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'npmjs.com',           name: 'npm',            policyType: 'terms_of_service', priority: 2 },
  { domain: 'stackoverflow.com',   name: 'Stack Overflow', policyType: 'privacy_policy',   priority: 2 },
  { domain: 'stackoverflow.com',   name: 'Stack Overflow', policyType: 'terms_of_service', priority: 3 },
  { domain: 'replit.com',          name: 'Replit',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'replit.com',          name: 'Replit',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'supabase.com',        name: 'Supabase',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'supabase.com',        name: 'Supabase',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'mongodb.com',         name: 'MongoDB',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'snowflake.com',       name: 'Snowflake',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'databricks.com',      name: 'Databricks',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'algolia.com',         name: 'Algolia',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'contentful.com',      name: 'Contentful',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'render.com',          name: 'Render',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'fly.io',              name: 'Fly.io',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'semrush.com',         name: 'SEMrush',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'ahrefs.com',          name: 'Ahrefs',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hootsuite.com',       name: 'Hootsuite',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'buffer.com',          name: 'Buffer',         policyType: 'privacy_policy',   priority: 4 },
  { domain: 'freshdesk.com',       name: 'Freshdesk',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'linear.app',          name: 'Linear',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'github.com',          name: 'GitHub',         product: 'Actions / CI',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'circleci.com',        name: 'CircleCI',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'logrocket.com',       name: 'LogRocket',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'posthog.com',         name: 'PostHog',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'cloudinary.com',      name: 'Cloudinary',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'sanity.io',           name: 'Sanity',         policyType: 'privacy_policy',   priority: 4 },

  // ── Education ─────────────────────────────────────────────────────────────
  { domain: 'coursera.org',        name: 'Coursera',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'coursera.org',        name: 'Coursera',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'udemy.com',           name: 'Udemy',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'udemy.com',           name: 'Udemy',          product: 'Instructor',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'khanacademy.org',     name: 'Khan Academy',   policyType: 'privacy_policy',   priority: 2, notes: 'Used by children — student data' },
  { domain: 'duolingo.com',        name: 'Duolingo',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'chegg.com',           name: 'Chegg',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'quizlet.com',         name: 'Quizlet',        policyType: 'privacy_policy',   priority: 2, notes: 'Student data including study habits and academic content' },
  { domain: 'turnitin.com',        name: 'Turnitin',       policyType: 'privacy_policy',   priority: 2, notes: 'Student writing submitted for plagiarism detection' },
  { domain: 'blackboard.com',      name: 'Blackboard',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'instructure.com',     name: 'Canvas',         product: 'Student Data',        policyType: 'data_processing_agreement', priority: 2 },
  { domain: 'collegeboard.org',    name: 'College Board',  policyType: 'privacy_policy',   priority: 2, notes: 'SAT scores, AP data, college applications' },
  { domain: 'commonapp.org',       name: 'Common App',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'edx.org',             name: 'edX',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'masterclass.com',     name: 'MasterClass',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'pluralsight.com',     name: 'Pluralsight',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'codecademy.com',      name: 'Codecademy',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'datacamp.com',        name: 'DataCamp',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'skillshare.com',      name: 'Skillshare',     policyType: 'privacy_policy',   priority: 4 },
  { domain: 'pearson.com',         name: 'Pearson',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'chegg.com',           name: 'Chegg',          policyType: 'terms_of_service', priority: 3 },
  { domain: 'scribd.com',          name: 'Scribd',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'brilliant.org',       name: 'Brilliant',      policyType: 'privacy_policy',   priority: 4 },

  // ── AI / ML Services ──────────────────────────────────────────────────────
  { domain: 'huggingface.co',      name: 'Hugging Face',   policyType: 'privacy_policy',   priority: 2 },
  { domain: 'huggingface.co',      name: 'Hugging Face',   policyType: 'terms_of_service', priority: 2 },
  { domain: 'stability.ai',        name: 'Stability AI',   policyType: 'privacy_policy',   priority: 2 },
  { domain: 'stability.ai',        name: 'Stability AI',   policyType: 'terms_of_service', priority: 2 },
  { domain: 'midjourney.com',      name: 'Midjourney',     policyType: 'privacy_policy',   priority: 2, notes: 'Image generation — prompt data and generated content ownership' },
  { domain: 'midjourney.com',      name: 'Midjourney',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'runwayml.com',        name: 'Runway',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'runwayml.com',        name: 'Runway',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'character.ai',        name: 'Character.AI',   policyType: 'privacy_policy',   priority: 2, notes: 'Conversation data with AI personas — popular with minors' },
  { domain: 'character.ai',        name: 'Character.AI',   policyType: 'terms_of_service', priority: 2 },
  { domain: 'perplexity.ai',       name: 'Perplexity',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'perplexity.ai',       name: 'Perplexity',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'mistral.ai',          name: 'Mistral AI',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'mistral.ai',          name: 'Mistral AI',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'cohere.com',          name: 'Cohere',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'cohere.com',          name: 'Cohere',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'elevenlabs.io',       name: 'ElevenLabs',     policyType: 'privacy_policy',   priority: 2, notes: 'Voice cloning — biometric voice data' },
  { domain: 'elevenlabs.io',       name: 'ElevenLabs',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'suno.ai',             name: 'Suno',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'suno.ai',             name: 'Suno',           policyType: 'terms_of_service', priority: 3 },
  { domain: 'replicate.com',       name: 'Replicate',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'replicate.com',       name: 'Replicate',      policyType: 'terms_of_service', priority: 3 },
  { domain: 'together.ai',         name: 'Together AI',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'openrouter.ai',       name: 'OpenRouter',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'heygen.com',          name: 'HeyGen',         policyType: 'privacy_policy',   priority: 3, notes: 'AI video avatars — face and voice data' },
  { domain: 'heygen.com',          name: 'HeyGen',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'pika.art',            name: 'Pika',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'luma.ai',             name: 'Luma AI',        policyType: 'privacy_policy',   priority: 3 },

  // ── Crypto / Web3 ─────────────────────────────────────────────────────────
  { domain: 'metamask.io',         name: 'MetaMask',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'metamask.io',         name: 'MetaMask',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'opensea.io',          name: 'OpenSea',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'opensea.io',          name: 'OpenSea',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'ledger.com',          name: 'Ledger',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'blockchain.com',      name: 'Blockchain.com', policyType: 'privacy_policy',   priority: 2 },
  { domain: 'uniswap.org',         name: 'Uniswap',        policyType: 'privacy_policy',   priority: 3 },

  // ── Dating ────────────────────────────────────────────────────────────────
  { domain: 'tinder.com',          name: 'Tinder',         policyType: 'privacy_policy',   priority: 1, notes: 'Location, photos, sexual preference data' },
  { domain: 'tinder.com',          name: 'Tinder',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'bumble.com',          name: 'Bumble',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'bumble.com',          name: 'Bumble',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'hinge.co',            name: 'Hinge',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'hinge.co',            name: 'Hinge',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'match.com',           name: 'Match',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'okcupid.com',         name: 'OkCupid',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'grindr.com',          name: 'Grindr',         policyType: 'privacy_policy',   priority: 1, notes: 'Sexual orientation data — previously sold to third parties' },
  { domain: 'grindr.com',          name: 'Grindr',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'eharmony.com',        name: 'eHarmony',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'pof.com',             name: 'Plenty of Fish', policyType: 'privacy_policy',   priority: 3 },

  // ── Smart Home / IoT ──────────────────────────────────────────────────────
  { domain: 'ring.com',            name: 'Ring',           policyType: 'privacy_policy',   priority: 1, notes: 'Home video surveillance — footage shared with police without warrant' },
  { domain: 'ring.com',            name: 'Ring',           policyType: 'terms_of_service', priority: 1 },
  { domain: 'nest.com',            name: 'Google Nest',    policyType: 'privacy_policy',   priority: 1, notes: 'In-home sensors, camera, thermostat data' },
  { domain: 'wyze.com',            name: 'Wyze',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'simplisafe.com',      name: 'SimpliSafe',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'adt.com',             name: 'ADT',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'ecobee.com',          name: 'Ecobee',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'arlo.com',            name: 'Arlo',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'blink.com',           name: 'Blink',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'august.com',          name: 'August (Smart Locks)', policyType: 'privacy_policy', priority: 3 },
  { domain: 'meethue.com',         name: 'Philips Hue',    policyType: 'privacy_policy',   priority: 4 },
  { domain: 'eufy.com',            name: 'Eufy',           policyType: 'privacy_policy',   priority: 3 },

  // ── HR / Business ─────────────────────────────────────────────────────────
  { domain: 'workday.com',         name: 'Workday',        policyType: 'privacy_policy',   priority: 2, notes: 'Employee data including salary, performance, HR records' },
  { domain: 'workday.com',         name: 'Workday',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'adp.com',             name: 'ADP',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'gusto.com',           name: 'Gusto',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'gusto.com',           name: 'Gusto',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'rippling.com',        name: 'Rippling',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'bamboohr.com',        name: 'BambooHR',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'deel.com',            name: 'Deel',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'remote.com',          name: 'Remote',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'greenhouse.io',       name: 'Greenhouse',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'glassdoor.com',       name: 'Glassdoor',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'glassdoor.com',       name: 'Glassdoor',      policyType: 'terms_of_service', priority: 3 },
  { domain: 'ziprecruiter.com',    name: 'ZipRecruiter',   policyType: 'privacy_policy',   priority: 3 },
  { domain: 'monster.com',         name: 'Monster',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'upwork.com',          name: 'Upwork',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'upwork.com',          name: 'Upwork',         product: 'Freelancer',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'fiverr.com',          name: 'Fiverr',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'fiverr.com',          name: 'Fiverr',         product: 'Seller',              policyType: 'terms_of_service', priority: 2 },
  { domain: 'handshake.com',       name: 'Handshake',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'wellfound.com',       name: 'Wellfound (AngelList)', policyType: 'privacy_policy', priority: 3 },

  // ── Government ────────────────────────────────────────────────────────────
  { domain: 'irs.gov',             name: 'IRS',            policyType: 'privacy_policy',   priority: 1 },
  { domain: 'ssa.gov',             name: 'Social Security Administration', policyType: 'privacy_policy', priority: 1 },
  { domain: 'uscis.gov',           name: 'USCIS',          policyType: 'privacy_policy',   priority: 1 },
  { domain: 'healthcare.gov',      name: 'Healthcare.gov', policyType: 'privacy_policy',   priority: 1, notes: 'ACA marketplace — health and income data' },
  { domain: 'va.gov',              name: 'VA',             policyType: 'privacy_policy',   priority: 1 },
  { domain: 'medicare.gov',        name: 'Medicare',       policyType: 'privacy_policy',   priority: 1 },
  { domain: 'cdc.gov',             name: 'CDC',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'fda.gov',             name: 'FDA',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'usa.gov',             name: 'USA.gov',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'state.gov',           name: 'US State Department', policyType: 'privacy_policy', priority: 3 },

  // ── Real Estate ───────────────────────────────────────────────────────────
  { domain: 'realtor.com',         name: 'Realtor.com',    policyType: 'privacy_policy',   priority: 2 },
  { domain: 'redfin.com',          name: 'Redfin',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'redfin.com',          name: 'Redfin',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'trulia.com',          name: 'Trulia',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'apartments.com',      name: 'Apartments.com', policyType: 'privacy_policy',   priority: 3 },
  { domain: 'rent.com',            name: 'Rent.com',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'costar.com',          name: 'CoStar',         policyType: 'privacy_policy',   priority: 4 },

  // ── Sports / Gambling ─────────────────────────────────────────────────────
  { domain: 'nfl.com',             name: 'NFL',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'nfl.com',             name: 'NFL',            policyType: 'terms_of_service', priority: 3 },
  { domain: 'nba.com',             name: 'NBA',            policyType: 'privacy_policy',   priority: 2 },
  { domain: 'mlb.com',             name: 'MLB',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'nhl.com',             name: 'NHL',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'fifa.com',            name: 'FIFA',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'draftkings.com',      name: 'DraftKings',     policyType: 'privacy_policy',   priority: 1, notes: 'Sports gambling — financial and betting behavior data' },
  { domain: 'draftkings.com',      name: 'DraftKings',     policyType: 'terms_of_service', priority: 1 },
  { domain: 'fanduel.com',         name: 'FanDuel',        policyType: 'privacy_policy',   priority: 1 },
  { domain: 'fanduel.com',         name: 'FanDuel',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'ticketmaster.com',    name: 'Ticketmaster',   policyType: 'privacy_policy',   priority: 2 },
  { domain: 'ticketmaster.com',    name: 'Ticketmaster',   policyType: 'terms_of_service', priority: 2 },
  { domain: 'stubhub.com',         name: 'StubHub',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'seatgeek.com',        name: 'SeatGeek',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'fanatics.com',        name: 'Fanatics',       policyType: 'privacy_policy',   priority: 3 },

  // ── VPN / Security / Privacy Tools ───────────────────────────────────────
  { domain: 'nordvpn.com',         name: 'NordVPN',        policyType: 'privacy_policy',   priority: 2, notes: 'Ironic priority — a VPN\'s own data practices matter a lot' },
  { domain: 'nordvpn.com',         name: 'NordVPN',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'expressvpn.com',      name: 'ExpressVPN',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'proton.me',           name: 'Proton',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'proton.me',           name: 'Proton',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'mullvad.net',         name: 'Mullvad VPN',    policyType: 'privacy_policy',   priority: 2 },
  { domain: '1password.com',       name: '1Password',      policyType: 'privacy_policy',   priority: 2 },
  { domain: '1password.com',       name: '1Password',      policyType: 'terms_of_service', priority: 2 },
  { domain: 'lastpass.com',        name: 'LastPass',       policyType: 'privacy_policy',   priority: 2, notes: 'Password manager — notable breach history' },
  { domain: 'bitwarden.com',       name: 'Bitwarden',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'dashlane.com',        name: 'Dashlane',       policyType: 'privacy_policy',   priority: 3 },

  // ── Kids / Family ─────────────────────────────────────────────────────────
  { domain: 'youtube.com',         name: 'YouTube',        product: 'YouTube Kids',        policyType: 'privacy_policy',   priority: 1, notes: 'COPPA-regulated — child data collection' },
  { domain: 'youtube.com',         name: 'YouTube',        product: 'YouTube Kids',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'disney.com',          name: 'Disney',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'disney.com',          name: 'Disney',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'nick.com',            name: 'Nickelodeon',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'pbskids.org',         name: 'PBS Kids',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'duolingo.com',        name: 'Duolingo',       product: 'Duolingo for Schools', policyType: 'privacy_policy', priority: 2 },
  { domain: 'roblox.com',          name: 'Roblox',         product: 'Under 13 / Child Account', policyType: 'privacy_policy', priority: 1, notes: 'COPPA applies — separate child data policy' },

  // ── Maps / Navigation ─────────────────────────────────────────────────────
  { domain: 'waze.com',            name: 'Waze',           policyType: 'privacy_policy',   priority: 2, notes: 'Real-time location data shared with Google' },
  { domain: 'waze.com',            name: 'Waze',           policyType: 'terms_of_service', priority: 3 },
  { domain: 'mapbox.com',          name: 'Mapbox',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'mapbox.com',          name: 'Mapbox',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'here.com',            name: 'HERE Maps',      policyType: 'privacy_policy',   priority: 3 },

  // ── Legal / Documents ─────────────────────────────────────────────────────
  { domain: 'legalzoom.com',       name: 'LegalZoom',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'rocketlawyer.com',    name: 'Rocket Lawyer',  policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hellosign.com',       name: 'HelloSign',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'notarize.com',        name: 'Notarize',       policyType: 'privacy_policy',   priority: 3, notes: 'Identity verification + legal document data' },

  // ── Productivity / Notes ──────────────────────────────────────────────────
  { domain: 'evernote.com',        name: 'Evernote',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'evernote.com',        name: 'Evernote',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'todoist.com',         name: 'Todoist',        policyType: 'privacy_policy',   priority: 4 },
  { domain: 'obsidian.md',         name: 'Obsidian',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'bear.app',            name: 'Bear',           policyType: 'privacy_policy',   priority: 4 },
  { domain: 'craft.do',            name: 'Craft',          policyType: 'privacy_policy',   priority: 4 },

  // ── Misc high-traffic ─────────────────────────────────────────────────────
  { domain: 'archive.org',         name: 'Internet Archive', policyType: 'privacy_policy', priority: 3 },
  { domain: 'wolframalpha.com',     name: 'Wolfram Alpha',  policyType: 'privacy_policy',  priority: 4 },
  { domain: 'change.org',          name: 'Change.org',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'kickstarter.com',     name: 'Kickstarter',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'indiegogo.com',       name: 'Indiegogo',      policyType: 'privacy_policy',   priority: 4 },
  { domain: 'gofundme.com',        name: 'GoFundMe',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'gofundme.com',        name: 'GoFundMe',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'ifixit.com',          name: 'iFixit',         policyType: 'privacy_policy',   priority: 5 },
  { domain: 'producthunt.com',     name: 'Product Hunt',   policyType: 'privacy_policy',   priority: 4 },
  { domain: 'goodreads.com',       name: 'Goodreads',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'letterboxd.com',      name: 'Letterboxd',     policyType: 'privacy_policy',   priority: 4 },
  { domain: 'rottentomatoes.com',  name: 'Rotten Tomatoes', policyType: 'privacy_policy',  priority: 4 },
  { domain: 'metacritic.com',      name: 'Metacritic',     policyType: 'privacy_policy',   priority: 5 },
  { domain: 'pinterest.com',       name: 'Pinterest',      product: 'Creator',             policyType: 'terms_of_service', priority: 4 },
  { domain: 'apple.com',           name: 'Apple',          product: 'Health / HealthKit',  policyType: 'privacy_policy',   priority: 1, notes: 'Health data aggregator from wearables and apps' },
  { domain: 'google.com',          name: 'Google',         product: 'Fit / Health',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'amazon.com',          name: 'Amazon',         product: 'Halo Health',         policyType: 'privacy_policy',   priority: 2, notes: 'Body composition and voice tone analysis' },
  { domain: 'microsoft.com',       name: 'Microsoft',      product: 'Teams',               policyType: 'privacy_policy',   priority: 1, notes: 'Work video/chat — transcripts, recordings, presence data' },
  { domain: 'microsoft.com',       name: 'Microsoft',      product: 'Teams',               policyType: 'terms_of_service', priority: 1 },
  { domain: 'google.com',          name: 'Google',         product: 'Meet',                policyType: 'privacy_policy',   priority: 2 },
  { domain: 'apple.com',           name: 'Apple',          product: 'FaceTime',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'microsoft.com',       name: 'Microsoft',      product: 'Azure AI / OpenAI Service', policyType: 'data_processing_agreement', priority: 2 },
  { domain: 'amazon.com',          name: 'Amazon',         product: 'Rekognition (Facial Recognition)', policyType: 'terms_of_service', priority: 1, notes: 'AI facial recognition sold to law enforcement' },
  { domain: 'snapchat.com',        name: 'Snap',           product: 'My AI',               policyType: 'privacy_policy',   priority: 2, notes: 'In-app AI chatbot with access to location and snaps' },
  { domain: 'meta.com',            name: 'Meta',           product: 'Meta AI',             policyType: 'privacy_policy',   priority: 1 },
  { domain: 'x.com',               name: 'X',              product: 'xAI / Grok (in-app)', policyType: 'privacy_policy',   priority: 2 },
  { domain: 'samsung.com',         name: 'Samsung',        product: 'Galaxy AI',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'google.com',          name: 'Google',         product: 'Assistant / Home',    policyType: 'privacy_policy',   priority: 1 },
  { domain: 'amazon.com',          name: 'Amazon',         product: 'AWS Bedrock',         policyType: 'privacy_policy',   priority: 2 },
];

async function add(c: C) {
  const res = await fetch(`${BASE}/admin/candidates`, {
    method: 'POST', headers,
    body: JSON.stringify({ domain: c.domain, name: c.name, product: c.product ?? null, policyType: c.policyType, priority: c.priority, notes: c.notes ?? null }),
  });
  const data = await res.json() as any;
  const label = `${c.domain}${c.product ? ' / ' + c.product : ''} [${c.policyType}]`;
  console.log(res.status === 201 ? `  ✓  ${label}` : `  ✗  ${label}: ${JSON.stringify(data?.error ?? data)}`);
}

async function run() {
  console.log(`\nPart 2: ${CANDIDATES.length} candidates...\n`);
  for (const c of CANDIDATES) await add(c);
  console.log('\nPart 2 done.');
}
run().catch(err => { console.error(err); process.exit(1); });
