import { config as loadEnv } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
loadEnv({ path: resolve(dirname(fileURLToPath(import.meta.url)), '../.env') });

const BASE = 'http://localhost:3000';
const SECRET = process.env.ADMIN_SECRET!;
const headers = { 'Content-Type': 'application/json', 'X-Admin-Secret': SECRET };

type PT = 'privacy_policy' | 'terms_of_service' | 'data_processing_agreement' | 'acceptable_use_policy';
interface C { domain: string; name: string; product?: string; policyType: PT; priority: number; notes?: string; }

const CANDIDATES: C[] = [
  // ── Social / Messaging ────────────────────────────────────────────────────
  { domain: 'snapchat.com',        name: 'Snap',           policyType: 'privacy_policy',   priority: 1, notes: 'Ephemeral content + location data' },
  { domain: 'snapchat.com',        name: 'Snap',           policyType: 'terms_of_service', priority: 2 },
  { domain: 'signal.org',          name: 'Signal',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'signal.org',          name: 'Signal',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'mastodon.social',     name: 'Mastodon',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'skype.com',           name: 'Microsoft',      product: 'Skype',               policyType: 'privacy_policy',   priority: 3 },
  { domain: 'line.me',             name: 'Line',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'line.me',             name: 'Line',           policyType: 'terms_of_service', priority: 3 },
  { domain: 'viber.com',           name: 'Viber',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'kik.com',             name: 'Kik',            policyType: 'privacy_policy',   priority: 4 },
  { domain: 'bereal.com',          name: 'BeReal',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'bereal.com',          name: 'BeReal',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'clubhouse.com',       name: 'Clubhouse',      policyType: 'privacy_policy',   priority: 4 },

  // ── Streaming / Video ─────────────────────────────────────────────────────
  { domain: 'hulu.com',            name: 'Hulu',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'hulu.com',            name: 'Hulu',           policyType: 'terms_of_service', priority: 2 },
  { domain: 'peacocktv.com',       name: 'Peacock',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'peacocktv.com',       name: 'Peacock',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'paramountplus.com',   name: 'Paramount+',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'paramountplus.com',   name: 'Paramount+',     policyType: 'terms_of_service', priority: 3 },
  { domain: 'crunchyroll.com',     name: 'Crunchyroll',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'crunchyroll.com',     name: 'Crunchyroll',    policyType: 'terms_of_service', priority: 4 },
  { domain: 'plex.tv',             name: 'Plex',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'plex.tv',             name: 'Plex',           policyType: 'terms_of_service', priority: 3 },
  { domain: 'tubi.tv',             name: 'Tubi',           policyType: 'privacy_policy',   priority: 4 },
  { domain: 'sling.com',           name: 'Sling TV',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'fubo.tv',             name: 'FuboTV',         policyType: 'privacy_policy',   priority: 4 },
  { domain: 'discoveryplus.com',   name: 'Discovery+',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'max.com',             name: 'Max (HBO)',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'max.com',             name: 'Max (HBO)',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'vimeo.com',           name: 'Vimeo',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'vimeo.com',           name: 'Vimeo',          policyType: 'terms_of_service', priority: 3 },
  { domain: 'vimeo.com',           name: 'Vimeo',          product: 'Creator',             policyType: 'terms_of_service', priority: 3 },
  { domain: 'dailymotion.com',     name: 'Dailymotion',    policyType: 'privacy_policy',   priority: 4 },
  { domain: 'rumble.com',          name: 'Rumble',         policyType: 'privacy_policy',   priority: 4 },

  // ── Music ─────────────────────────────────────────────────────────────────
  { domain: 'soundcloud.com',      name: 'SoundCloud',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'soundcloud.com',      name: 'SoundCloud',     policyType: 'terms_of_service', priority: 3 },
  { domain: 'soundcloud.com',      name: 'SoundCloud',     product: 'Artist / Uploader',   policyType: 'terms_of_service', priority: 3 },
  { domain: 'pandora.com',         name: 'Pandora',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'pandora.com',         name: 'Pandora',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'siriusxm.com',        name: 'SiriusXM',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'siriusxm.com',        name: 'SiriusXM',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'deezer.com',          name: 'Deezer',         policyType: 'privacy_policy',   priority: 4 },
  { domain: 'tidal.com',           name: 'Tidal',          policyType: 'privacy_policy',   priority: 4 },
  { domain: 'bandcamp.com',        name: 'Bandcamp',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'bandcamp.com',        name: 'Bandcamp',       product: 'Artist',              policyType: 'terms_of_service', priority: 4 },
  { domain: 'audible.com',         name: 'Audible',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'audible.com',         name: 'Audible',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'audiomack.com',       name: 'Audiomack',      policyType: 'privacy_policy',   priority: 5 },

  // ── E-commerce / Retail ───────────────────────────────────────────────────
  { domain: 'shopify.com',         name: 'Shopify',        policyType: 'privacy_policy',   priority: 1, notes: 'Powers millions of storefronts — massive data intermediary' },
  { domain: 'shopify.com',         name: 'Shopify',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'shopify.com',         name: 'Shopify',        product: 'Merchant',            policyType: 'terms_of_service', priority: 1, notes: 'What customer data merchants can access and how Shopify uses it' },
  { domain: 'target.com',          name: 'Target',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'target.com',          name: 'Target',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'bestbuy.com',         name: 'Best Buy',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'bestbuy.com',         name: 'Best Buy',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'homedepot.com',       name: 'Home Depot',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'lowes.com',           name: "Lowe's",         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'costco.com',          name: 'Costco',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'ikea.com',            name: 'IKEA',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'wayfair.com',         name: 'Wayfair',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'wayfair.com',         name: 'Wayfair',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'nike.com',            name: 'Nike',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'nike.com',            name: 'Nike',           policyType: 'terms_of_service', priority: 3 },
  { domain: 'adidas.com',          name: 'Adidas',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'nordstrom.com',       name: 'Nordstrom',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'macys.com',           name: "Macy's",         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'gap.com',             name: 'Gap',            policyType: 'privacy_policy',   priority: 4 },
  { domain: 'hm.com',              name: 'H&M',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'zara.com',            name: 'Zara',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'chewy.com',           name: 'Chewy',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'newegg.com',          name: 'Newegg',         policyType: 'privacy_policy',   priority: 4 },
  { domain: 'poshmark.com',        name: 'Poshmark',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'poshmark.com',        name: 'Poshmark',       product: 'Seller',              policyType: 'terms_of_service', priority: 3 },
  { domain: 'mercari.com',         name: 'Mercari',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'mercari.com',         name: 'Mercari',        product: 'Seller',              policyType: 'terms_of_service', priority: 3 },
  { domain: 'depop.com',           name: 'Depop',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'depop.com',           name: 'Depop',          product: 'Seller',              policyType: 'terms_of_service', priority: 3 },
  { domain: 'craigslist.org',      name: 'Craigslist',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'offerup.com',         name: 'OfferUp',        policyType: 'privacy_policy',   priority: 4 },
  { domain: 'wish.com',            name: 'Wish',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'overstock.com',       name: 'Overstock',      policyType: 'privacy_policy',   priority: 4 },
  { domain: 'rakuten.com',         name: 'Rakuten Rewards', policyType: 'privacy_policy',  priority: 3 },
  { domain: 'groupon.com',         name: 'Groupon',        policyType: 'privacy_policy',   priority: 4 },
  { domain: 'reverb.com',          name: 'Reverb',         policyType: 'privacy_policy',   priority: 4 },
  { domain: 'woocommerce.com',     name: 'WooCommerce',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'woocommerce.com',     name: 'WooCommerce',    policyType: 'terms_of_service', priority: 3 },

  // ── Food / Delivery ───────────────────────────────────────────────────────
  { domain: 'doordash.com',        name: 'DoorDash',       policyType: 'privacy_policy',   priority: 1 },
  { domain: 'doordash.com',        name: 'DoorDash',       policyType: 'terms_of_service', priority: 1 },
  { domain: 'doordash.com',        name: 'DoorDash',       product: 'Dasher / Driver',     policyType: 'terms_of_service', priority: 1, notes: 'Location tracking, earnings, deactivation terms' },
  { domain: 'doordash.com',        name: 'DoorDash',       product: 'Restaurant Partner',  policyType: 'terms_of_service', priority: 2 },
  { domain: 'ubereats.com',        name: 'Uber Eats',      policyType: 'privacy_policy',   priority: 1 },
  { domain: 'ubereats.com',        name: 'Uber Eats',      policyType: 'terms_of_service', priority: 1 },
  { domain: 'grubhub.com',         name: 'Grubhub',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'grubhub.com',         name: 'Grubhub',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'grubhub.com',         name: 'Grubhub',        product: 'Restaurant Partner',  policyType: 'terms_of_service', priority: 2 },
  { domain: 'instacart.com',       name: 'Instacart',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'instacart.com',       name: 'Instacart',      policyType: 'terms_of_service', priority: 2 },
  { domain: 'instacart.com',       name: 'Instacart',      product: 'Shopper',             policyType: 'terms_of_service', priority: 2 },
  { domain: 'yelp.com',            name: 'Yelp',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'yelp.com',            name: 'Yelp',           policyType: 'terms_of_service', priority: 2 },
  { domain: 'yelp.com',            name: 'Yelp',           product: 'Business Owner',      policyType: 'terms_of_service', priority: 2 },
  { domain: 'opentable.com',       name: 'OpenTable',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'opentable.com',       name: 'OpenTable',      product: 'Restaurant',          policyType: 'terms_of_service', priority: 3 },
  { domain: 'chipotle.com',        name: 'Chipotle',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'starbucks.com',       name: 'Starbucks',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'mcdonalds.com',       name: "McDonald's",     policyType: 'privacy_policy',   priority: 4 },
  { domain: 'dominos.com',         name: "Domino's",       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'seamless.com',        name: 'Seamless',       policyType: 'privacy_policy',   priority: 5 },

  // ── Travel ────────────────────────────────────────────────────────────────
  { domain: 'airbnb.com',          name: 'Airbnb',         policyType: 'privacy_policy',   priority: 1 },
  { domain: 'airbnb.com',          name: 'Airbnb',         policyType: 'terms_of_service', priority: 1 },
  { domain: 'airbnb.com',          name: 'Airbnb',         product: 'Host',                policyType: 'terms_of_service', priority: 1, notes: 'Guest data access, payout terms, damage protection' },
  { domain: 'uber.com',            name: 'Uber',           policyType: 'privacy_policy',   priority: 1 },
  { domain: 'uber.com',            name: 'Uber',           policyType: 'terms_of_service', priority: 1 },
  { domain: 'uber.com',            name: 'Uber',           product: 'Driver / Earner',     policyType: 'terms_of_service', priority: 1, notes: 'Location data, deactivation, earnings' },
  { domain: 'lyft.com',            name: 'Lyft',           policyType: 'privacy_policy',   priority: 1 },
  { domain: 'lyft.com',            name: 'Lyft',           policyType: 'terms_of_service', priority: 1 },
  { domain: 'lyft.com',            name: 'Lyft',           product: 'Driver',              policyType: 'terms_of_service', priority: 1 },
  { domain: 'expedia.com',         name: 'Expedia',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'expedia.com',         name: 'Expedia',        policyType: 'terms_of_service', priority: 2 },
  { domain: 'kayak.com',           name: 'KAYAK',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'trivago.com',         name: 'Trivago',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hotels.com',          name: 'Hotels.com',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'vrbo.com',            name: 'VRBO',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'vrbo.com',            name: 'VRBO',           product: 'Host',                policyType: 'terms_of_service', priority: 3 },
  { domain: 'marriott.com',        name: 'Marriott',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'marriott.com',        name: 'Marriott',       policyType: 'terms_of_service', priority: 3 },
  { domain: 'hilton.com',          name: 'Hilton',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hilton.com',          name: 'Hilton',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'delta.com',           name: 'Delta Airlines', policyType: 'privacy_policy',   priority: 2 },
  { domain: 'delta.com',           name: 'Delta Airlines', policyType: 'terms_of_service', priority: 3 },
  { domain: 'united.com',          name: 'United Airlines', policyType: 'privacy_policy',  priority: 2 },
  { domain: 'aa.com',              name: 'American Airlines', policyType: 'privacy_policy', priority: 2 },
  { domain: 'southwest.com',       name: 'Southwest Airlines', policyType: 'privacy_policy', priority: 2 },
  { domain: 'spirit.com',          name: 'Spirit Airlines', policyType: 'privacy_policy',  priority: 4 },
  { domain: 'tripadvisor.com',     name: 'Tripadvisor',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'priceline.com',       name: 'Priceline',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hopper.com',          name: 'Hopper',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'turo.com',            name: 'Turo',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'turo.com',            name: 'Turo',           product: 'Host / Car Owner',    policyType: 'terms_of_service', priority: 3 },
  { domain: 'getaround.com',       name: 'Getaround',      policyType: 'privacy_policy',   priority: 4 },

  // ── Fintech / Banking ─────────────────────────────────────────────────────
  { domain: 'venmo.com',           name: 'Venmo',          policyType: 'privacy_policy',   priority: 1 },
  { domain: 'venmo.com',           name: 'Venmo',          policyType: 'terms_of_service', priority: 1 },
  { domain: 'cash.app',            name: 'Cash App',       policyType: 'privacy_policy',   priority: 1 },
  { domain: 'cash.app',            name: 'Cash App',       policyType: 'terms_of_service', priority: 1 },
  { domain: 'zellepay.com',        name: 'Zelle',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'robinhood.com',       name: 'Robinhood',      policyType: 'privacy_policy',   priority: 1 },
  { domain: 'robinhood.com',       name: 'Robinhood',      policyType: 'terms_of_service', priority: 1 },
  { domain: 'coinbase.com',        name: 'Coinbase',       policyType: 'privacy_policy',   priority: 1 },
  { domain: 'coinbase.com',        name: 'Coinbase',       policyType: 'terms_of_service', priority: 1 },
  { domain: 'binance.com',         name: 'Binance',        policyType: 'privacy_policy',   priority: 1 },
  { domain: 'binance.com',         name: 'Binance',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'kraken.com',          name: 'Kraken',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'crypto.com',          name: 'Crypto.com',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'gemini.com',          name: 'Gemini Exchange', policyType: 'privacy_policy',  priority: 2 },
  { domain: 'affirm.com',          name: 'Affirm',         policyType: 'privacy_policy',   priority: 2, notes: 'BNPL — credit and purchase data' },
  { domain: 'affirm.com',          name: 'Affirm',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'klarna.com',          name: 'Klarna',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'klarna.com',          name: 'Klarna',         policyType: 'terms_of_service', priority: 2 },
  { domain: 'afterpay.com',        name: 'Afterpay',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'chime.com',           name: 'Chime',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'chime.com',           name: 'Chime',          policyType: 'terms_of_service', priority: 2 },
  { domain: 'sofi.com',            name: 'SoFi',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'creditkarma.com',     name: 'Credit Karma',   policyType: 'privacy_policy',   priority: 1, notes: 'Aggregates credit, income, and tax data' },
  { domain: 'creditkarma.com',     name: 'Credit Karma',   policyType: 'terms_of_service', priority: 1 },
  { domain: 'plaid.com',           name: 'Plaid',          policyType: 'privacy_policy',   priority: 1, notes: 'Bank account data intermediary — reads transaction history' },
  { domain: 'plaid.com',           name: 'Plaid',          policyType: 'terms_of_service', priority: 1 },
  { domain: 'stripe.com',          name: 'Stripe',         policyType: 'privacy_policy',   priority: 1 },
  { domain: 'stripe.com',          name: 'Stripe',         policyType: 'terms_of_service', priority: 1 },
  { domain: 'stripe.com',          name: 'Stripe',         product: 'Merchant / Developer', policyType: 'terms_of_service', priority: 1, notes: 'Customer payment data handling for businesses' },
  { domain: 'squareup.com',        name: 'Square / Block', policyType: 'privacy_policy',   priority: 1 },
  { domain: 'squareup.com',        name: 'Square / Block', policyType: 'terms_of_service', priority: 1 },
  { domain: 'squareup.com',        name: 'Square / Block', product: 'Merchant',            policyType: 'terms_of_service', priority: 1 },
  { domain: 'chase.com',           name: 'JPMorgan Chase', policyType: 'privacy_policy',   priority: 1 },
  { domain: 'bankofamerica.com',   name: 'Bank of America', policyType: 'privacy_policy',  priority: 1 },
  { domain: 'wellsfargo.com',      name: 'Wells Fargo',    policyType: 'privacy_policy',   priority: 1 },
  { domain: 'citi.com',            name: 'Citibank',       policyType: 'privacy_policy',   priority: 1 },
  { domain: 'capitalone.com',      name: 'Capital One',    policyType: 'privacy_policy',   priority: 1 },
  { domain: 'discover.com',        name: 'Discover',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'americanexpress.com', name: 'American Express', policyType: 'privacy_policy', priority: 1 },
  { domain: 'schwab.com',          name: 'Charles Schwab', policyType: 'privacy_policy',   priority: 2 },
  { domain: 'fidelity.com',        name: 'Fidelity',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'vanguard.com',        name: 'Vanguard',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'wise.com',            name: 'Wise',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'revolut.com',         name: 'Revolut',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'nerdwallet.com',      name: 'NerdWallet',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'experian.com',        name: 'Experian',       policyType: 'privacy_policy',   priority: 1, notes: 'Credit bureau — highly sensitive data' },
  { domain: 'equifax.com',         name: 'Equifax',        policyType: 'privacy_policy',   priority: 1 },
  { domain: 'transunion.com',      name: 'TransUnion',     policyType: 'privacy_policy',   priority: 1 },
  { domain: 'acorns.com',          name: 'Acorns',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'betterment.com',      name: 'Betterment',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'wealthfront.com',     name: 'Wealthfront',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'mint.intuit.com',     name: 'Intuit Mint',    policyType: 'privacy_policy',   priority: 2 },
  { domain: 'turbotax.intuit.com', name: 'TurboTax',       policyType: 'privacy_policy',   priority: 1, notes: 'Tax return data including SSN, income, dependents' },
  { domain: 'hrblock.com',         name: 'H&R Block',      policyType: 'privacy_policy',   priority: 1 },

  // ── Health / Fitness ──────────────────────────────────────────────────────
  { domain: 'myfitnesspal.com',    name: 'MyFitnessPal',   policyType: 'privacy_policy',   priority: 2, notes: 'Diet, weight, calorie tracking' },
  { domain: 'myfitnesspal.com',    name: 'MyFitnessPal',   policyType: 'terms_of_service', priority: 3 },
  { domain: 'strava.com',          name: 'Strava',         policyType: 'privacy_policy',   priority: 2, notes: 'GPS route data — can reveal home/work locations' },
  { domain: 'strava.com',          name: 'Strava',         policyType: 'terms_of_service', priority: 3 },
  { domain: 'peloton.com',         name: 'Peloton',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'peloton.com',         name: 'Peloton',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'headspace.com',       name: 'Headspace',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'calm.com',            name: 'Calm',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'goodrx.com',          name: 'GoodRx',         policyType: 'privacy_policy',   priority: 1, notes: 'Prescription drug searches — highly sensitive' },
  { domain: 'goodrx.com',          name: 'GoodRx',         policyType: 'terms_of_service', priority: 1 },
  { domain: 'webmd.com',           name: 'WebMD',          policyType: 'privacy_policy',   priority: 2 },
  { domain: 'healthline.com',      name: 'Healthline',     policyType: 'privacy_policy',   priority: 3 },
  { domain: 'mayoclinic.org',      name: 'Mayo Clinic',    policyType: 'privacy_policy',   priority: 3 },
  { domain: 'teladoc.com',         name: 'Teladoc',        policyType: 'privacy_policy',   priority: 1, notes: 'Telehealth — medical records and consultations' },
  { domain: 'zocdoc.com',          name: 'ZocDoc',         policyType: 'privacy_policy',   priority: 2 },
  { domain: '23andme.com',         name: '23andMe',        policyType: 'privacy_policy',   priority: 1, notes: 'Genetic data — most sensitive category possible' },
  { domain: '23andme.com',         name: '23andMe',        policyType: 'terms_of_service', priority: 1 },
  { domain: 'ancestry.com',        name: 'Ancestry',       policyType: 'privacy_policy',   priority: 1, notes: 'Genetic + family tree data' },
  { domain: 'ancestry.com',        name: 'Ancestry',       policyType: 'terms_of_service', priority: 1 },
  { domain: 'fitbit.com',          name: 'Fitbit',         policyType: 'privacy_policy',   priority: 2 },
  { domain: 'garmin.com',          name: 'Garmin',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'ouraring.com',        name: 'Oura',           policyType: 'privacy_policy',   priority: 2, notes: 'Sleep, HRV, temperature biometrics' },
  { domain: 'whoop.com',           name: 'WHOOP',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'noom.com',            name: 'Noom',           policyType: 'privacy_policy',   priority: 2 },
  { domain: 'ww.com',              name: 'WeightWatchers', policyType: 'privacy_policy',   priority: 3 },
  { domain: 'alltrails.com',       name: 'AllTrails',      policyType: 'privacy_policy',   priority: 4 },
  { domain: 'nike.com',            name: 'Nike',           product: 'Nike Run Club / Training', policyType: 'privacy_policy', priority: 3 },
  { domain: 'withings.com',        name: 'Withings',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'dexcom.com',          name: 'Dexcom',         policyType: 'privacy_policy',   priority: 2, notes: 'Continuous glucose monitor data' },
  { domain: 'epic.com',            name: 'Epic Systems',   policyType: 'privacy_policy',   priority: 1, notes: 'EHR platform used by major hospitals — patient records' },
  { domain: 'mychart.com',         name: 'MyChart / Epic', policyType: 'privacy_policy',   priority: 1 },

  // ── Gaming ────────────────────────────────────────────────────────────────
  { domain: 'steampowered.com',    name: 'Valve / Steam',  policyType: 'privacy_policy',   priority: 1 },
  { domain: 'steampowered.com',    name: 'Valve / Steam',  policyType: 'terms_of_service', priority: 1 },
  { domain: 'steampowered.com',    name: 'Valve / Steam',  product: 'Developer / Publisher', policyType: 'terms_of_service', priority: 2 },
  { domain: 'epicgames.com',       name: 'Epic Games',     policyType: 'privacy_policy',   priority: 1 },
  { domain: 'epicgames.com',       name: 'Epic Games',     policyType: 'terms_of_service', priority: 1 },
  { domain: 'epicgames.com',       name: 'Epic Games',     product: 'Developer / Unreal', policyType: 'terms_of_service', priority: 2 },
  { domain: 'ea.com',              name: 'Electronic Arts', policyType: 'privacy_policy',  priority: 2 },
  { domain: 'ea.com',              name: 'Electronic Arts', policyType: 'terms_of_service', priority: 2 },
  { domain: 'activision.com',      name: 'Activision',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'activision.com',      name: 'Activision',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'blizzard.com',        name: 'Blizzard',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'blizzard.com',        name: 'Blizzard',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'riotgames.com',       name: 'Riot Games',     policyType: 'privacy_policy',   priority: 2 },
  { domain: 'riotgames.com',       name: 'Riot Games',     policyType: 'terms_of_service', priority: 2 },
  { domain: 'nintendo.com',        name: 'Nintendo',       policyType: 'privacy_policy',   priority: 2 },
  { domain: 'nintendo.com',        name: 'Nintendo',       policyType: 'terms_of_service', priority: 2 },
  { domain: 'playstation.com',     name: 'Sony PlayStation', policyType: 'privacy_policy', priority: 2 },
  { domain: 'playstation.com',     name: 'Sony PlayStation', policyType: 'terms_of_service', priority: 2 },
  { domain: 'ubisoft.com',         name: 'Ubisoft',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'ubisoft.com',         name: 'Ubisoft',        policyType: 'terms_of_service', priority: 3 },
  { domain: 'minecraft.net',       name: 'Minecraft / Mojang', policyType: 'privacy_policy', priority: 2 },
  { domain: 'minecraft.net',       name: 'Minecraft / Mojang', policyType: 'terms_of_service', priority: 2 },
  { domain: 'gog.com',             name: 'GOG',            policyType: 'privacy_policy',   priority: 4 },
  { domain: 'itch.io',             name: 'itch.io',        policyType: 'privacy_policy',   priority: 4 },
  { domain: 'itch.io',             name: 'itch.io',        product: 'Developer',           policyType: 'terms_of_service', priority: 4 },
  { domain: 'chess.com',           name: 'Chess.com',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'rockstargames.com',   name: 'Rockstar Games', policyType: 'privacy_policy',   priority: 3 },
  { domain: 'bethesda.net',        name: 'Bethesda',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'hoyoverse.com',       name: 'HoYoverse',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'supercell.com',       name: 'Supercell',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'king.com',            name: 'King (Candy Crush)', policyType: 'privacy_policy', priority: 3 },
  { domain: 'pokemongolive.com',   name: 'Pokémon GO / Niantic', policyType: 'privacy_policy', priority: 2, notes: 'Location data constantly tracked' },
  { domain: 'nianticlabs.com',     name: 'Niantic',        policyType: 'privacy_policy',   priority: 2 },
  { domain: 'twitch.tv',           name: 'Twitch',         product: 'Developer / Extensions', policyType: 'terms_of_service', priority: 4 },

  // ── News / Media ──────────────────────────────────────────────────────────
  { domain: 'washingtonpost.com',  name: 'Washington Post', policyType: 'privacy_policy',  priority: 2 },
  { domain: 'wsj.com',             name: 'Wall Street Journal', policyType: 'privacy_policy', priority: 2 },
  { domain: 'reuters.com',         name: 'Reuters',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'apnews.com',          name: 'AP News',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'bloomberg.com',       name: 'Bloomberg',      policyType: 'privacy_policy',   priority: 2 },
  { domain: 'theatlantic.com',     name: 'The Atlantic',   policyType: 'privacy_policy',   priority: 3 },
  { domain: 'vox.com',             name: 'Vox',            policyType: 'privacy_policy',   priority: 4 },
  { domain: 'foxnews.com',         name: 'Fox News',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'npr.org',             name: 'NPR',            policyType: 'privacy_policy',   priority: 3 },
  { domain: 'politico.com',        name: 'Politico',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'axios.com',           name: 'Axios',          policyType: 'privacy_policy',   priority: 3 },
  { domain: 'techcrunch.com',      name: 'TechCrunch',     policyType: 'privacy_policy',   priority: 4 },
  { domain: 'theverge.com',        name: 'The Verge',      policyType: 'privacy_policy',   priority: 4 },
  { domain: 'wired.com',           name: 'Wired',          policyType: 'privacy_policy',   priority: 4 },
  { domain: 'arstechnica.com',     name: 'Ars Technica',   policyType: 'privacy_policy',   priority: 4 },
  { domain: 'businessinsider.com', name: 'Business Insider', policyType: 'privacy_policy', priority: 4 },
  { domain: 'forbes.com',          name: 'Forbes',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'time.com',            name: 'Time',           policyType: 'privacy_policy',   priority: 3 },
  { domain: 'usatoday.com',        name: 'USA Today',      policyType: 'privacy_policy',   priority: 3 },
  { domain: 'cbsnews.com',         name: 'CBS News',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'nbcnews.com',         name: 'NBC News',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'abcnews.go.com',      name: 'ABC News',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'nypost.com',          name: 'NY Post',        policyType: 'privacy_policy',   priority: 4 },
  { domain: 'latimes.com',         name: 'LA Times',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'huffpost.com',        name: 'HuffPost',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'buzzfeed.com',        name: 'BuzzFeed',       policyType: 'privacy_policy',   priority: 4 },
  { domain: 'substack.com',        name: 'Substack',       policyType: 'privacy_policy',   priority: 3 },
  { domain: 'substack.com',        name: 'Substack',       product: 'Writer / Publisher',  policyType: 'terms_of_service', priority: 3 },
  { domain: 'medium.com',          name: 'Medium',         policyType: 'privacy_policy',   priority: 3 },
  { domain: 'medium.com',          name: 'Medium',         product: 'Writer',              policyType: 'terms_of_service', priority: 3 },
  { domain: 'patreon.com',         name: 'Patreon',        policyType: 'privacy_policy',   priority: 3 },
  { domain: 'patreon.com',         name: 'Patreon',        product: 'Creator',             policyType: 'terms_of_service', priority: 2, notes: 'Revenue share and fan data access for creators' },
];

async function add(c: C) {
  const res = await fetch(`${BASE}/admin/candidates`, {
    method: 'POST', headers,
    body: JSON.stringify({ domain: c.domain, name: c.name, product: c.product ?? null, policyType: c.policyType, priority: c.priority, notes: c.notes ?? null }),
  });
  const data = await res.json() as any;
  const label = `${c.domain}${c.product ? ' / ' + c.product : ''} [${c.policyType}]`;
  console.log(res.status === 201 ? `  ✓  ${label}` : `  ✗  ${label}: ${JSON.stringify(data?.error ?? data)}`);
}

async function run() {
  console.log(`\nPart 1: ${CANDIDATES.length} candidates...\n`);
  for (const c of CANDIDATES) await add(c);
  console.log('\nPart 1 done.');
}
run().catch(err => { console.error(err); process.exit(1); });
